version: '3.8'
services:
  # MySQL Database
  db:
    image: mysql:8.0  # Updated MySQL version
    container_name: mysql-db
    restart: always  # Ensures MySQL restarts if it crashes
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # CodeIgniter 4 RESTful API (PHP 8.2)
  api:
    build: ./proWebAPI
    container_name: codeigniter-api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./proWebAPI:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=codeigniter
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db

  # Angular 19 Frontend (Nginx)
  frontend:
    build: ./proSPA
    container_name: angular-frontend
    restart: always
    depends_on:
      - api
    ports:
      - "4200:4200"  # Ensure Angular runs on the correct port
    volumes:
      - ./proSPA/dist:/usr/share/nginx/html  # Persist Angular build files

# Top-level volumes definition
volumes:
  mysql-data:
