version: '3.8'

services:
  angular:
    build:
      context: .
    container_name: angular-app
    ports:
      - "4200:4200"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
